name: Bug Report
description: You found a bug
labels: [bug]
assignees: DevDyna
body:
  - type: checkboxes
    id: check-base
    attributes:
      label: Base
      description: Stuff that need to be checked!
      options:
        - label: I have checked all other issues on this project
          required: true
        - label: I'am using the latest version of this project released
          required: true

  - type: checkboxes
    id: optional
    attributes:
      label: Optional
      description: optional-desc
      options:
        - label: 1-option
          required: false
        - label: 2-option
          required: false
          
        
  - type: input
    id: text-box
    attributes:
      label: Text Box
      placeholder: example
      description: desc-box
    validations:
      required: true

  - type: textarea
    id: large-text-box
    attributes:
      label: Large Text Box
      description: desc-large-box
      placeholder: example
    validations:
      required: true
      
