name: Bug Report
description: You found a bug
labels: [bug]
assignees: DevDyna
body:

  - type: checkboxes
    id: new-issue
    attributes:
      label: Core Section
      description: Things that need to be checked!
      options:
        - label: I have searched on opened [issues](https://github.com/DevDyna/EasyBee/issues) and [discussions](https://github.com/DevDyna/EasyBee/discussions) of this repository
          required: true
        - label: I'm using the latest version of this project
          required: true


 - type: input
   id: text-box
   attributes:
      label: Mod Loader Version
      placeholder: forge-1.0
      description: Write what version of modloader was used
    validations:
      required: true

 - type: textarea
   id: large-text-box-1
   attributes:
      label: Description
      description: Describe what happen
      placeholder: sqrt(-1) - sqrt(i) = -0,707106781 + 0,292893219 i
    validations:
      required: true

  - type: textarea
    id: large-text-box-2
    attributes:
      label: Procedure
      description: Describe how to reproduce it
      placeholder: sqrt(-1) - sqrt(i) = -0,707106781 + 0,292893219 i
    validations:
      required: false
      
