name: Simple Text
description: You found a bug
labels: [bug]
assignees: DevDyna
body:
  - type: textarea
    id: large-text-box
    attributes:
      label: Description
      description: Describe what you want that i add on this project
      placeholder: 
    validations:
      required: true
